---
# Set paths
data_file: MET_M120x4_13k_25Jul23.mat  # Location of MATLAB file containing processed input data
output_dir: data/results   # Location to save training results (new folder will be created within output_dir)

# Set experiment properties:
experiment_name: test  # Name of experiment (used to create output folder)
num_epochs: 2500   # Number of epochs to train
latent_dim: 5   # Dimension of latent space for each modality
batch_size: 1000   # Batch size used during training
dropout: 0.2   # Dropout probability
gauss_var_frac: 0.05   # Fraction of data variance to insert as data augmentation
fold: 0   # Which of the tenfold cross validations to use
learning_rate: 0.001   # Learning rate for the ADAM optimizer

# Set model hyperparameters
alpha_T: 1.0   # T reconstruction loss weight coefficient
alpha_E: 42.1   # E reconstruction loss weight coefficient
alpha_M: 0.281   # M reconstruction loss weight coefficient
alpha_ME: 2.69   # ME reconstruction loss weight coefficient
lambda_E_T: 0.566   # E_T coupling loss weight coefficient
lambda_M_T: 0.533   # M_T coupling loss weight coefficient
lambda_ME_T: 0.00892   # ME_T coupling loss weight coefficient
lambda_T_E: 22.0   # T_E coupling loss weight coefficient
lambda_T_M: 23.8   # T_M coupling loss weight coefficient
lambda_T_ME: 357.8   # T_ME coupling loss weight coefficient
lambda_ME_E: 259.8   # ME_E coupling loss weight coefficient
lambda_ME_M: 308.0   # ME_M coupling loss weight coefficient
