package_dir = "/home/fahimehb/Local/code/cplAE_MET/"
remote_dir = "/home/fahimehb/Remote-AI-root/allen/programs/celltypes/workgroups/rnaseqanalysis/Fahimehb/git_workspace/cplAE_MET/data/"
MET_data = "/home/fahimehb/Remote-AI-root/allen/programs/celltypes/workgroups/mousecelltypes/MachineLearning/Patchseq-Exc/dat/MET_M120x4_13k_25Jul23.mat"
